### ISSUE TITLE
Please release one stable version with all the fixes which are pending in PR.

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#78] opened 2016-05-25 09:25 UTC
I think most of the code is getting fixed on daily basis so how can I get that latest fixes in my current code, and once you release that how can I upgrade my code to that?

**Comment by Stupidism** [comment] 2016-05-25 09:30
If you don't mind some half-work. Try 

```
git clone this-repo
git checkout develop
npm link
```

then your global generator-material-app will link to this local project

**Comment by TejasCMehta** [comment] 2016-05-25 10:32
sure, I will try this and let you know!!

**Comment by michaelkrone** [comment] 2016-05-26 19:22
Duplicate of #66

**Closed as completed by michaelkrone** 2016-05-26 19:22 UTC
